plugins {
    id 'java'
}

group 'terraform-lambda-java'
version '1.0-SNAPSHOT'

sourceCompatibility = 17

repositories {
    mavenCentral()
}

dependencies {
    testImplementation('junit:junit:4.13.1')

    implementation('com.amazonaws:aws-lambda-java-core:1.3.0')
    implementation('com.amazonaws:aws-lambda-java-events:3.16.1')
    runtimeOnly('com.amazonaws:aws-lambda-java-log4j2:1.6.0')
    runtimeOnly('joda-time:joda-time:2.14.0')
}

task copyThirdPartyJars(type: Copy) {
    // Specify the source for the JARs. This example assumes you want to copy
    // all JARs from the 'runtimeClasspath' configuration.
    from configurations.runtimeClasspath

    // Set the destination directory where the JARs will be copied.
    // In this example, it's a directory named "libs" inside the build directory.
    into "$buildDir/libs"

    // Optional: Filter the files to only include JAR files.
    // You could also add other includes/excludes based on your needs.
    include '**/aws-lambda-java-events*.jar'
    include '**/joda-time*.jar'
}

tasks.withType(Jar) {
    dependsOn copyThirdPartyJars

    into('lib') {
        from "$buildDir/libs"
    }
    destinationDir = file("$rootDir/output/")
}
